version: "3.8"
services:
  mysql_springboot_container:
    image: mysql:latest
    container_name: mysql_springboot_container
    ports:
      - 3310:3306
    volumes:
      - mysql_spring_data:/var/lib/mysql
      - mysql_spring_config_deamond:/etc/mysql/conf.d
    # restart:
    networks:
      - apinetwork
    environment:
      MYSQL_DATABASE: manager_library
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root

  manager_library_container:
    image: kidkender/manager_library:latest
    container_name: manager_library_container
    # restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8181:8181
    volumes:
      - ./:/backend
    networks:
      - apinetwork

networks:
  apinetwork:
    external:
      name: springboot_app_network

volumes:
  mysql_spring_data:
  mysql_spring_config_deamond:
